import Peer, { type MediaConnection, type DataConnection } from 'peerjs';

// PeerJS IDs are global across their public broker, so we prefix ours to
// avoid collisions with anyone else testing against the same free service.
export function peerIdForResident(residentId: string): string {
  return `intercom-resident-${residentId}`;
}
function panelPeerId(siteId: string): string {
  return `intercom-panel-${siteId}-${Math.random().toString(36).slice(2, 8)}`;
}

type ControlMessage = { type: 'declined' | 'cancelled' | 'ended' | 'door_opened' };

export type LocalMediaMode = 'video+audio' | 'audio-only' | 'video-only' | 'none';

export class PanelCaller {
  private peer: Peer | null = null;
  private call: MediaConnection | null = null;
  private dataConn: DataConnection | null = null;
  private localStream: MediaStream | null = null;
  localMediaMode: LocalMediaMode = 'none';

  async init(siteId: string): Promise<void> {
    this.peer = new Peer(panelPeerId(siteId), {
      host: 'intercom-peerjs-server-production.up.railway.app',
      path: '/peerjs',
      secure: true,
      port: 443,
      config: {
        iceServers: [
          { urls: 'stun:stun.l.google.com:19302' },
          { urls: 'stun:stun1.l.google.com:19302' },
        ],
        iceTransportPolicy: 'all',
        sdpSemantics: 'unified-plan',
      },
    });
    await new Promise<void>((resolve, reject) => {
      this.peer!.on('open', () => resolve());
      this.peer!.on('error', (err) => reject(err));
    });
  }

  // Acquire whatever local media is actually available, degrading gracefully
  // instead of failing the whole call. This matters on the Pi specifically:
  // (1) the CSI ribbon camera is a RAW Bayer sensor under libcamera, which
  // Chromium's getUserMedia cannot consume at all until the v4l2loopback
  // bridge is running (see daemon repo: scripts/camera-loopback.sh), and
  // (2) there is no microphone until the USB audio hardware exists. The old
  // behavior — getUserMedia({video:true,audio:true}) or die — meant either
  // missing device killed the call before signaling even started, which
  // presented as "Calling..." forever with no error.
  private async acquireLocalMedia(): Promise<MediaStream> {
    const audioConstraints = { echoCancellation: true, noiseSuppression: true, autoGainControl: true };

    try {
      const s = await navigator.mediaDevices.getUserMedia({ video: true, audio: audioConstraints });
      this.localMediaMode = 'video+audio';
      return s;
    } catch { /* fall through */ }

    try {
      const s = await navigator.mediaDevices.getUserMedia({ audio: audioConstraints });
      this.localMediaMode = 'audio-only';
      console.warn('[PanelCaller] no usable camera — calling audio-only');
      return s;
    } catch { /* fall through */ }

    try {
      const s = await navigator.mediaDevices.getUserMedia({ video: true });
      this.localMediaMode = 'video-only';
      console.warn('[PanelCaller] no usable microphone — calling with video only');
      return s;
    } catch { /* fall through */ }

    // No local media at all — still place the call so signaling works and
    // the resident can at least answer/unlock. Their side sends audio/video
    // fine; ours sends nothing until camera/mic hardware is available.
    this.localMediaMode = 'none';
    console.warn('[PanelCaller] no camera or microphone available — placing signaling-only call');
    return new MediaStream();
  }

  // One-way video from the panel (visitor's camera), two-way audio — matches
  // the decided call flow: resident sees/hears visitor, visitor only hears
  // resident until the resident opts to enable their own camera.
  //
  // Also opens a DataConnection purely for control signaling (decline/
  // cancel/end). MediaConnection.close() alone doesn't reliably tell the
  // other side a call ended — especially before it's been answered, when
  // the media handshake isn't fully established yet — which is why decline
  // and cancel previously left the other side hanging indefinitely.
  async callResident(
    residentId: string,
    onRemoteStream: (stream: MediaStream) => void,
    onClose: (reason?: 'door_opened') => void,
    metadata?: Record<string, unknown>,
  ): Promise<void> {
    if (!this.peer) throw new Error('Caller not initialized');
    this.localStream = await this.acquireLocalMedia();

    // WebRTC requires at least one media track to negotiate — an empty
    // MediaStream (our 'none' fallback) silently fails to trigger the
    // 'call' event on the resident's side because there's nothing to
    // negotiate. Fix: add a silent audio track generated by the Web Audio
    // API. This is essentially free (no mic access needed, just an
    // oscillator running at 0 gain), and it forces a proper WebRTC
    // handshake so the resident actually gets the incoming call ring.
    if (this.localStream.getTracks().length === 0) {
      try {
        const ctx = new AudioContext();
        const oscillator = ctx.createOscillator();
        const dst = ctx.createMediaStreamDestination();
        const gainNode = ctx.createGain();
        gainNode.gain.value = 0; // completely silent
        oscillator.connect(gainNode);
        gainNode.connect(dst);
        oscillator.start();
        dst.stream.getAudioTracks().forEach(t => this.localStream!.addTrack(t));
      } catch {
        // AudioContext unavailable — as a last resort, create a silent track
        // directly. This is less reliable but covers environments where
        // AudioContext itself is blocked.
        console.warn('[PanelCaller] AudioContext unavailable, call may not reach resident');
      }
    }

    this.call = this.peer.call(peerIdForResident(residentId), this.localStream, { metadata });
    console.log('[PanelCaller] calling peer:', peerIdForResident(residentId), 'with tracks:', this.localStream.getTracks().map(t => t.kind + ':' + t.label));
    this.call.on('stream', (remoteStream) => onRemoteStream(remoteStream));
    this.call.on('close', () => onClose());
    this.call.on('error', () => onClose());

    this.dataConn = this.peer.connect(peerIdForResident(residentId));
    this.dataConn.on('data', (data) => {
      const msg = data as ControlMessage;
      if (msg?.type === 'door_opened') onClose('door_opened');
      else if (msg?.type === 'declined' || msg?.type === 'ended') onClose();
    });
  }

  // Waits briefly after sending a control message before the caller tears
  // anything down - dataConn.send() only queues the message, it doesn't
  // guarantee transmission before the function returns. Destroying the
  // connection immediately after sending was a real race that explained
  // "call doesn't close on the other side" happening intermittently rather
  // than consistently.
  async sendControlAndWait(type: ControlMessage['type']): Promise<void> {
    if (this.dataConn?.open) {
      this.dataConn.send({ type });
      await new Promise((resolve) => setTimeout(resolve, 250));
    }
  }

  sendControl(type: ControlMessage['type']): void {
    if (this.dataConn?.open) this.dataConn.send({ type });
  }

  getLocalStream(): MediaStream | null {
    return this.localStream;
  }

  hangUp(): void {
    this.call?.close();
    this.dataConn?.close();
    this.localStream?.getTracks().forEach((t) => t.stop());
    this.localStream = null;
  }

  destroy(): void {
    this.hangUp();
    this.peer?.destroy();
    this.peer = null;
  }
}
